from .job_title import JobTitle
from .academic_field import AcademicField
from .degress import Degrees
from .academic_history import AcademicHistory
from .languages import Languages
from .user_language import UserLanguage
from .skill import Skill
from .user_skill import UserSkill
from .work_experiences import WorkExperiences
