# Generated by Django 6.0.4 on 2026-05-08 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicField',
            fields=[
                ('academic_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(help_text='Nombre del campo academico(ej. Ingenieria de sistemas)', max_length=200, unique=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Campo Académico',
                'verbose_name_plural': 'Campos Académicos',
                'db_table': 'academic_field',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Grado Académico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Grado Académico',
                'verbose_name_plural': 'Grados Académicos',
                'db_table': 'degrees',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('languages_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'db_table': 'languages',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Habilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'skill',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('academic_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('institution_name', models.CharField(help_text='Universidad, instituto o centro de estudios', max_length=255, verbose_name='Nombre de la Institución')),
                ('speciality', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad/Mención')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('academic_field_id', models.ForeignKey(db_column='academic_field_id', on_delete=django.db.models.deletion.PROTECT, to='core.academicfield', verbose_name='Campo Académico')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='academic_histories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('degree_id', models.ForeignKey(db_column='degree_id', on_delete=django.db.models.deletion.PROTECT, to='core.degrees', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'verbose_name_plural': 'Historiales Académicos',
                'db_table': 'academic_history',
                'ordering': ['-start_date', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('user_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=3, help_text='Autoevaluación de su dominio en esta habilidad (1: Básico - 4: Experto)', verbose_name='Nivel de Competencia')),
                ('skill_id', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='Habilidad')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Habilidad de Usuario',
                'verbose_name_plural': 'Habilidades de Usuarios',
                'db_table': 'users_skills',
            },
        ),
        migrations.CreateModel(
            name='WorkExperiences',
            fields=[
                ('work_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enterprise_name', models.CharField(help_text='Nombre de la empresa o institución donde laboró', max_length=255, verbose_name='Empresa')),
                ('responsibilities', models.TextField(blank=True, help_text='Liste sus principales funciones y responsabilidades en el cargo', null=True, verbose_name='Responsabilidades')),
                ('description', models.TextField(blank=True, help_text='Breve resumen de su rol dentro de la organización', null=True, verbose_name='Descripción del Puesto')),
                ('achievement', models.TextField(blank=True, help_text='Mencione metas alcanzadas o proyectos exitosos', null=True, verbose_name='Logros')),
                ('start_date', models.DateField(help_text='Fecha en la que comenzó a laborar', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar en blanco si es su empleo actual', null=True, verbose_name='Fecha de Finalización')),
                ('job_title_id', models.ForeignKey(blank=True, db_column='job_title_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobtitle', verbose_name='Puesto de Trabajo')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'db_table': 'work_experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('user_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.CharField(choices=[('BASIC', 'Básico'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado'), ('FLUENT', 'Fluido'), ('NATIVE', 'Nativo')], default='INTERMEDIATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to='core.languages')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idioma del Usuario',
                'verbose_name_plural': 'Idiomas de Usuarios',
                'db_table': 'users_info_languages',
                'unique_together': {('user_id', 'language_id')},
            },
        ),
    ]
