# Generated by Django 6.0.4 on 2026-05-20 22:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicfield_degrees_languages_skill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['name'], 'verbose_name': 'Puesto de Trabajo', 'verbose_name_plural': 'Puestos de Trabajo'},
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del puesto'),
        ),
        migrations.AlterModelTable(
            name='jobtitle',
            table='job_title',
        ),
    ]
